name             'rails-demo'
maintainer       'coddeys'
maintainer_email 'coddeys@gmail.com'
license          'All rights reserved'
description      'Installs/Configures rails-demo'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
depends          'git'
depends          'application'
depends          'application_ruby'
